Controllers/CakesController.cs
using asp_exam_iliyana.Models.ViewModels;
using asp_exam_iliyana.Services.Interfaces;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace asp_exam_iliyana.Controllers
{
    public class CakesController : Controller
    {
        private readonly ICakeService _cakeService;
        private readonly IMapper _mapper;

        public CakesController(ICakeService cakeService, IMapper mapper)
        {
            _cakeService = cakeService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var cakes = await _cakeService.GetAllCakesAsync();

            return View(cakes);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var cake = await _cakeService.GetCakeByIdAsync(id);
            return View(cake);
        }

    }
}

Controllers/OrdersController.cs
using asp_exam_iliyana.Models;
using asp_exam_iliyana.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace asp_exam_iliyana.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ICakeService _cakeService;
        private readonly SignInManager<User> _signInManager;

        public OrdersController(ICakeService cakeService, SignInManager<User> signInManager)
        {
            _cakeService = cakeService;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index(Guid CakeId)
        {
            var cake = await _cakeService.GetCakeByIdAsync(CakeId);
            var userId = _signInManager.Context.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var newOrder = new Order(userId, CakeId);

            return View();
        }
    }
}

Views/Shared/_AdminLayout.cshtml
@{
    Layout = "_Layout";
}

<div>
    <h2>Admin Panel</h2>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <partial name="_ManageNavAdmin" />
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

@RenderBody()

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/asp_exam_iliyana.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:antiquewhite">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/images/SiteLogo.png" height="50px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cakes" asp-action="Index">Cakes</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">My Orders</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:antiquewhite">
        <div class="container text-center">
            &copy; 2024 Iliyana Marinova - IT Step
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ManageNavAdmin.cshtml
<ul class="nav nav-pills flex-column">
    <li class="nav-item"><a class="nav-link @(ViewData["Title"] == "Index" ? "active" : "")" id="profile" asp-action="Index">Index</a></li>
    <li class="nav-item"><a class="nav-link @(ViewData["Title"] == "Users" ? "active" : "")" id="profile" asp-action="Users">Users</a></li>
    <li class="nav-item"><a class="nav-link @(ViewData["Title"] == "Roles" ? "active" : "")" id="profile" asp-action="Roles">Roles</a></li>
    <li class="nav-item"><a class="nav-link @(ViewData["Title"] == "Cakes" ? "active" : "")" id="profile" asp-action="Cakes">Cakes</a></li>
</ul>